# add_subdirectory(algebra)
# add_subdirectory(calculus)
# add_subdirectory(ccalculus)
# add_subdirectory(de)
# add_subdirectory(fcalculus)
add_subdirectory(geometry)
# add_subdirectory(logic)
# add_subdirectory(mechanics)
# add_subdirectory(mexmat)
# add_subdirectory(misc)
# add_subdirectory(nt)
add_subdirectory(ptms)
# add_subdirectory(rcalculus)
# add_subdirectory(varcalculus)
